-- MySQL Script generated by MySQL Workbench
-- Fri May 10 13:57:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autogest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autogest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autogest` DEFAULT CHARACTER SET utf8 ;
USE `autogest` ;

-- -----------------------------------------------------
-- Table `autogest`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autogest`.`Client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autogest`.`Vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autogest`.`Vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(255) NOT NULL,
  `license_plate` VARCHAR(45) NOT NULL,
  `kilometers` INT NOT NULL,
  `Client_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Vehicle_Client_idx` (`Client_id` ASC) VISIBLE,
  CONSTRAINT `fk_Vehicle_Client`
    FOREIGN KEY (`Client_id`)
    REFERENCES `autogest`.`Client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autogest`.`Loan_vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autogest`.`Loan_vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(255) NOT NULL,
  `license_plate` VARCHAR(45) NOT NULL,
  `kilometers` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autogest`.`Planning`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autogest`.`Planning` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `registration_date` DATETIME NOT NULL,
  `pickup_date` DATETIME NOT NULL,
  `Vehicle_id` INT NOT NULL,
  `Loan_vehicle_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Planning_Vehicle1_idx` (`Vehicle_id` ASC) VISIBLE,
  INDEX `fk_Planning_Loan_vehicle1_idx` (`Loan_vehicle_id` ASC) VISIBLE,
  CONSTRAINT `fk_Planning_Vehicle1`
    FOREIGN KEY (`Vehicle_id`)
    REFERENCES `autogest`.`Vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Planning_Loan_vehicle1`
    FOREIGN KEY (`Loan_vehicle_id`)
    REFERENCES `autogest`.`Loan_vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
